<?php
/**
 * Builds the CSS design tokens and the SVG icon sprite from design/source/*.json
 * (exported from Figma). Run after the design tokens change:
 *
 *   php tools/build-assets.php
 */
declare(strict_types=1);

$root = dirname(__DIR__);
$src = $root . '/design/source';
$out = $root . '/app/public/assets';

$t = json_decode((string) file_get_contents("$src/tokens.json"), true, flags: JSON_THROW_ON_ERROR);

$light = $dark = [];
foreach ($t['color'] as $name => [$l, $d]) {
    $light[] = "  --$name: $l;";
    $dark[] = "  --$name: $d;";
}
$scale = [];
foreach ($t['space'] as $k => $v) $scale[] = "  --space-$k: {$v}px;";
foreach ($t['radius'] as $k => $v) $scale[] = "  --radius-$k: {$v}px;";
foreach ($t['size'] as $k => $v) $scale[] = "  --size-$k: {$v}px;";
foreach ($t['font'] as $k => $v) $scale[] = "  --font-$k: $v;";
foreach ($t['shadow'] as $k => $v) $scale[] = "  --shadow-$k: $v;";

$text = [];
foreach ($t['text'] as $name => [$family, $weight, $size, $line, $track]) {
    $text[] = ".t-$name { font: $weight {$size}px/{$line}px var(--font-$family); letter-spacing: {$track}px; }";
}
$fa = [];
foreach ($t['text_fa'] as $name => [$weight, $size, $line]) {
    $fa[] = ":lang(fa) .t-$name { font: $weight {$size}px/{$line}px var(--font-fa); letter-spacing: 0; }";
}

$css = "/* Generated by tools/build-assets.php from design/source/tokens.json — do not edit by hand. */\n"
    . ":root {\n" . implode("\n", $light) . "\n" . implode("\n", $scale) . "\n}\n"
    . "[data-theme=\"dark\"] {\n" . implode("\n", $dark) . "\n}\n\n"
    . implode("\n", $text) . "\n"
    . ":lang(fa) [class*=\"t-\"] { font-family: var(--font-fa); letter-spacing: 0; }\n"
    . implode("\n", $fa) . "\n";
@mkdir("$out/css", 0777, true);
file_put_contents("$out/css/tokens.css", $css);

$icons = json_decode((string) file_get_contents("$src/icons.json"), true, flags: JSON_THROW_ON_ERROR);
$sprite = ['<svg xmlns="http://www.w3.org/2000/svg" style="display:none">'];
foreach ($icons as $name => $paths) {
    $body = implode('', array_map(static fn(string $d): string => '<path d="' . htmlspecialchars($d, ENT_QUOTES) . '"/>', $paths));
    $sprite[] = '<symbol id="i-' . $name . '" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round">' . $body . '</symbol>';
}
$sprite[] = '</svg>';
file_put_contents("$out/icons.svg", implode("\n", $sprite) . "\n");

printf("tokens.css: %d colours, %d text styles · icons.svg: %d icons\n", count($light), count($text), count($icons));
